# Generated by Django 5.0 on 2023-12-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('draft', models.BooleanField(default=True, verbose_name='draft')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('posted_at', models.DateTimeField(verbose_name='posted_at')),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
